DROP DATABASE IF EXISTS gloggerdb;
CREATE DATABASE gloggerdb;
USE gloggerdb;
CREATE TABLE User(id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, login VARCHAR(20) NOT NULL, password VARCHAR(20) NOT NULL, email VARCHAR(30) NOT NULL, first_layer_params TEXT, second_layer_params TEXT);
